// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SignalKo.SystemMonitor.Monitor.Web.Controllers {
    public partial class ConfigurationController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ConfigurationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ConfigurationController Actions { get { return MVC.Configuration; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Configuration";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Configuration";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string GetAgentConfigurationEditorViewModel = "GetAgentConfigurationEditorViewModel";
            public readonly string AgentConfiguration = "AgentConfiguration";
            public readonly string UIConfiguration = "UIConfiguration";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string GetAgentConfigurationEditorViewModel = "GetAgentConfigurationEditorViewModel";
            public const string AgentConfiguration = "AgentConfiguration";
            public const string UIConfiguration = "UIConfiguration";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AgentConfiguration = "~/Views/Configuration/AgentConfiguration.cshtml";
            public readonly string UIConfiguration = "~/Views/Configuration/UIConfiguration.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ConfigurationController: SignalKo.SystemMonitor.Monitor.Web.Controllers.ConfigurationController {
        public T4MVC_ConfigurationController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.JsonResult GetAgentConfigurationEditorViewModel() {
            var callInfo = new T4MVC_JsonResult(Area, Name, ActionNames.GetAgentConfigurationEditorViewModel);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AgentConfiguration() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AgentConfiguration);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult UIConfiguration() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.UIConfiguration);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
