// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace SignalKo.SystemMonitor.Monitor.Web.Controllers {
    public partial class GroupConfigurationController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GroupConfigurationController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected GroupConfigurationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditGroup() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditGroup);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GroupConfigurationController Actions { get { return MVC.GroupConfiguration; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "GroupConfiguration";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "GroupConfiguration";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string EditGroups = "EditGroups";
            public readonly string EditGroup = "EditGroup";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string EditGroups = "EditGroups";
            public const string EditGroup = "EditGroup";
        }


        static readonly ActionParamsClass_EditGroup s_params_EditGroup = new ActionParamsClass_EditGroup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditGroup EditGroupParams { get { return s_params_EditGroup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditGroup {
            public readonly string groupName = "groupName";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string EditGroup = "~/Views/GroupConfiguration/EditGroup.cshtml";
            public readonly string EditGroups = "~/Views/GroupConfiguration/EditGroups.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_GroupConfigurationController: SignalKo.SystemMonitor.Monitor.Web.Controllers.GroupConfigurationController {
        public T4MVC_GroupConfigurationController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult EditGroups() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditGroups);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditGroup(string groupName) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditGroup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "groupName", groupName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
