// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC
{
    public static SignalKo.SystemMonitor.Monitor.Web.Controllers.AgentConfigurationController AgentConfiguration = new SignalKo.SystemMonitor.Monitor.Web.Controllers.T4MVC_AgentConfigurationController();
    public static SignalKo.SystemMonitor.Monitor.Web.Controllers.ChartsController Charts = new SignalKo.SystemMonitor.Monitor.Web.Controllers.T4MVC_ChartsController();
    public static SignalKo.SystemMonitor.Monitor.Web.Controllers.UIConfigurationController UIConfiguration = new SignalKo.SystemMonitor.Monitor.Web.Controllers.T4MVC_UIConfigurationController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string global_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/global.min.js") ? Url("global.min.js") : Url("global.js");
                      
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class highcharts {
            private const string URLPATH = "~/Scripts/highcharts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string highcharts_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/highcharts.min.js") ? Url("highcharts.min.js") : Url("highcharts.js");
                          
            public static readonly string highcharts_theme_gray_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/highcharts.theme.gray.min.js") ? Url("highcharts.theme.gray.min.js") : Url("highcharts.theme.gray.js");
                          
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class libraries {
            private const string URLPATH = "~/Scripts/libraries";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string jquery_1_8_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.8.2.intellisense.min.js") ? Url("jquery-1.8.2.intellisense.min.js") : Url("jquery-1.8.2.intellisense.js");
                          
            public static readonly string jquery_1_8_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.8.2.min.js") ? Url("jquery-1.8.2.min.js") : Url("jquery-1.8.2.js");
                          
            public static readonly string jquery_1_8_2_min_js = Url("jquery-1.8.2.min.js");
            public static readonly string jquery_ui_1_9_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.9.0.min.js") ? Url("jquery-ui-1.9.0.min.js") : Url("jquery-ui-1.9.0.js");
                          
            public static readonly string jquery_ui_1_9_0_min_js = Url("jquery-ui-1.9.0.min.js");
            public static readonly string jquery_signalR_0_5_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.signalR-0.5.3.min.js") ? Url("jquery.signalR-0.5.3.min.js") : Url("jquery.signalR-0.5.3.js");
                          
            public static readonly string jquery_signalR_0_5_3_min_js = Url("jquery.signalR-0.5.3.min.js");
            public static readonly string knockout_2_2_0_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.2.0.debug.min.js") ? Url("knockout-2.2.0.debug.min.js") : Url("knockout-2.2.0.debug.js");
                          
            public static readonly string knockout_2_2_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-2.2.0.min.js") ? Url("knockout-2.2.0.min.js") : Url("knockout-2.2.0.js");
                          
            public static readonly string knockout_sortable_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout-sortable.min.js") ? Url("knockout-sortable.min.js") : Url("knockout-sortable.js");
                          
            public static readonly string knockout_sortable_min_js = Url("knockout-sortable.min.js");
            public static readonly string knockout_mapping_latest_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout.mapping-latest.debug.min.js") ? Url("knockout.mapping-latest.debug.min.js") : Url("knockout.mapping-latest.debug.js");
                          
            public static readonly string knockout_mapping_latest_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/knockout.mapping-latest.min.js") ? Url("knockout.mapping-latest.min.js") : Url("knockout.mapping-latest.js");
                          
            public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
                          
            public static readonly string underscore_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/underscore.min.js") ? Url("underscore.min.js") : Url("underscore.js");
                          
            public static readonly string underscore_min_js = Url("underscore.min.js");
            public static readonly string underscore_string_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/underscore.string.min.js") ? Url("underscore.string.min.js") : Url("underscore.string.js");
                          
            public static readonly string underscore_string_min_js = Url("underscore.string.min.js");
        }
    
        public static readonly string Systemmonitor_AgentConfiguration_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.AgentConfiguration.min.js") ? Url("Systemmonitor.AgentConfiguration.min.js") : Url("Systemmonitor.AgentConfiguration.js");
                      
        public static readonly string Systemmonitor_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.min.js") ? Url("Systemmonitor.min.js") : Url("Systemmonitor.js");
                      
        public static readonly string Systemmonitor_Layout_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.Layout.min.js") ? Url("Systemmonitor.Layout.min.js") : Url("Systemmonitor.Layout.js");
                      
        public static readonly string Systemmonitor_Overview_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.Overview.min.js") ? Url("Systemmonitor.Overview.min.js") : Url("Systemmonitor.Overview.js");
                      
        public static readonly string Systemmonitor_UIConfiguration_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.UIConfiguration.min.js") ? Url("Systemmonitor.UIConfiguration.min.js") : Url("Systemmonitor.UIConfiguration.js");
                      
        public static readonly string Systemmonitor_Utilities_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Systemmonitor.Utilities.min.js") ? Url("Systemmonitor.Utilities.min.js") : Url("Systemmonitor.Utilities.js");
                      
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Styles {
        private const string URLPATH = "~/Styles";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class assets {
            private const string URLPATH = "~/Styles/assets";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string icon_chart_ico = Url("icon-chart.ico");
            public static readonly string icon_chart_png = Url("icon-chart.png");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class source {
                private const string URLPATH = "~/Styles/assets/source";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class logo {
                    private const string URLPATH = "~/Styles/assets/source/logo";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string icon_chart_128_ico = Url("icon-chart-128.ico");
                    public static readonly string icon_chart_128_png = Url("icon-chart-128.png");
                    public static readonly string icon_chart_128_psd = Url("icon-chart-128.psd");
                    public static readonly string icon_chart_16_ico = Url("icon-chart-16.ico");
                    public static readonly string icon_chart_16_png = Url("icon-chart-16.png");
                    public static readonly string icon_chart_16_psd = Url("icon-chart-16.psd");
                    public static readonly string icon_chart_32_ico = Url("icon-chart-32.ico");
                    public static readonly string icon_chart_32_png = Url("icon-chart-32.png");
                    public static readonly string icon_chart_32_psd = Url("icon-chart-32.psd");
                    public static readonly string icon_chart_48_ico = Url("icon-chart-48.ico");
                    public static readonly string icon_chart_48_png = Url("icon-chart-48.png");
                    public static readonly string icon_chart_48_psd = Url("icon-chart-48.psd");
                    public static readonly string icon_chart_64_ico = Url("icon-chart-64.ico");
                    public static readonly string icon_chart_64_png = Url("icon-chart-64.png");
                    public static readonly string icon_chart_64_psd = Url("icon-chart-64.psd");
                    public static readonly string icon_chart_ai = Url("icon-chart.ai");
                }
            
            }
        
        }
    
        public static readonly string combine_chirp_config = Url("combine.chirp.config");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Combined {
            private const string URLPATH = "~/Styles/Combined";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string global_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/global.min.css") ? Url("global.min.css") : Url("global.css");
                 
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class jquery_ui {
                private const string URLPATH = "~/Styles/Combined/jquery-ui";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class overcast {
                    private const string URLPATH = "~/Styles/Combined/jquery-ui/overcast";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Styles/Combined/jquery-ui/overcast/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_0_eeeeee_40x100_png = Url("ui-bg_flat_0_eeeeee_40x100.png");
                        public static readonly string ui_bg_flat_55_c0402a_40x100_png = Url("ui-bg_flat_55_c0402a_40x100.png");
                        public static readonly string ui_bg_flat_55_eeeeee_40x100_png = Url("ui-bg_flat_55_eeeeee_40x100.png");
                        public static readonly string ui_bg_glass_100_f8f8f8_1x400_png = Url("ui-bg_glass_100_f8f8f8_1x400.png");
                        public static readonly string ui_bg_glass_35_dddddd_1x400_png = Url("ui-bg_glass_35_dddddd_1x400.png");
                        public static readonly string ui_bg_glass_60_eeeeee_1x400_png = Url("ui-bg_glass_60_eeeeee_1x400.png");
                        public static readonly string ui_bg_inset_hard_75_999999_1x100_png = Url("ui-bg_inset-hard_75_999999_1x100.png");
                        public static readonly string ui_bg_inset_soft_50_c9c9c9_1x100_png = Url("ui-bg_inset-soft_50_c9c9c9_1x100.png");
                        public static readonly string ui_icons_3383bb_256x240_png = Url("ui-icons_3383bb_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_70b2e1_256x240_png = Url("ui-icons_70b2e1_256x240.png");
                        public static readonly string ui_icons_999999_256x240_png = Url("ui-icons_999999_256x240.png");
                        public static readonly string ui_icons_fbc856_256x240_png = Url("ui-icons_fbc856_256x240.png");
                    }
                
                    public static readonly string jquery_ui_1_8_23_custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.8.23.custom.min.css") ? Url("jquery-ui-1.8.23.custom.min.css") : Url("jquery-ui-1.8.23.custom.css");
                         
                }
            
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class fonts {
            private const string URLPATH = "~/Styles/fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string fontawesome_webfont_eot = Url("fontawesome-webfont.eot");
            public static readonly string fontawesome_webfont_svg = Url("fontawesome-webfont.svg");
            public static readonly string fontawesome_webfont_ttf = Url("fontawesome-webfont.ttf");
            public static readonly string fontawesome_webfont_woff = Url("fontawesome-webfont.woff");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Source {
            private const string URLPATH = "~/Styles/Source";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string agent_configuration_chirp_less = Url("agent-configuration.chirp.less");
            public static readonly string agent_configuration_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/agent-configuration.min.css") ? Url("agent-configuration.min.css") : Url("agent-configuration.css");
                 
            public static readonly string agent_configuration_min_css = Url("agent-configuration.min.css");
            public static readonly string agent_group_overview_chirp_less = Url("agent-group-overview.chirp.less");
            public static readonly string agent_group_overview_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/agent-group-overview.min.css") ? Url("agent-group-overview.min.css") : Url("agent-group-overview.css");
                 
            public static readonly string agent_group_overview_min_css = Url("agent-group-overview.min.css");
            public static readonly string agent_group_chirp_less = Url("agent-group.chirp.less");
            public static readonly string agent_group_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/agent-group.min.css") ? Url("agent-group.min.css") : Url("agent-group.css");
                 
            public static readonly string agent_group_min_css = Url("agent-group.min.css");
            public static readonly string global_chirp_less = Url("global.chirp.less");
            public static readonly string global_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/global.min.css") ? Url("global.min.css") : Url("global.css");
                 
            public static readonly string global_min_css = Url("global.min.css");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class libraries {
                private const string URLPATH = "~/Styles/Source/libraries";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string font_awesome_chirp_less = Url("font-awesome.chirp.less");
                public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
                     
                public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
            }
        
            public static readonly string ui_configuration_chirp_less = Url("ui-configuration.chirp.less");
            public static readonly string ui_configuration_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ui-configuration.min.css") ? Url("ui-configuration.min.css") : Url("ui-configuration.css");
                 
            public static readonly string ui_configuration_min_css = Url("ui-configuration.min.css");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;


    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


